version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    container_name: server-app
    command: ["./server-app"] # Command to run the server binary
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080" # Expose port 8080

  client:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    container_name: client-app
    entrypoint: ["./client-app"] # Command to run the client binary
    stdin_open: true  # Keep stdin open for interaction
    tty: true         # Allocate a pseudo-TTY
    env_file:
      - .env